# Generated by Django 3.0.6 on 2020-05-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyuzi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, unique=True),
        ),
    ]
