# Generated by Django 3.0.6 on 2020-05-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyuzi', '0002_auto_20200520_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
